import java.util.*;
class Billprint{
	public static void main(String[] args){
	Scanner print = new Scanner(System.in);
	System.out.println("-------------------------------------------------------------------------------------           ");
	System.out.println("");
	System.out.println("__          __  _                             _          _ __  __            _                  ");
    System.out.println("\\ \\        / / | |                           | |        (_)  \\/  |          | |              ");
	System.out.println(" \\ \\  /\\  / /__| | ___ ___  _ ___ ___  ___   | |__ __    _| \\  / | __ _ _ __| |__           ");
	System.out.println("  \\ \\/  \\/ / _ \\ |/ __/ _ \\| '_  '_  \\/ _ \\  | __/ _ \\  | | |\\/| |/ _' | '__| ___|     ");
	System.out.println("   \\  /\\  /  __/ | (__|(_) | | | | | |  __/  | || (_) | | | |  | | (_) | |  | |__             ");
	System.out.println("    \\/  \\/\\____|_|\\___\\___/|_| |_| |_|\\___|  \\___\\___/  |_|_|  |_|\\__,_|_|   \\___|    ");
	System.out.println("");
	System.out.println("=====================================================================================           ");
	String tel,name;
	System.out.print("Enter Customer Phone Number -");
	tel = print.next();
	System.out.print("Enter Customer Name -");
	name = print.next();
	System.out.println("");
	System.out.println("=====================================================================================           ");
	int b,d,s,h,y,f,p;
	System.out.println("");
	System.out.println("");	
	System.out.print("Basmathi Qty(kg) -");
	b = print.nextInt();
	System.out.println("");
	System.out.print("Dhal Qty(kg) -" );
	d = print.nextInt();
	System.out.println("");
	System.out.print("Suger Qty(kg) -");
	s = print.nextInt();
	System.out.println("");
	System.out.print("Higland Qty -");
	h = print.nextInt();
	System.out.println("");
	System.out.print("Yoghurt Qty -");
	y = print.nextInt();
	System.out.println("");
	System.out.print("Flour Qty(kg) -");
	f = print.nextInt();
	System.out.println("");
	System.out.print("Soap Qty -");
	p = print.nextInt();
	System.out.println("");
	System.out.println("");
	System.out.println("");
	int ab,ad,as,ah,ay,af,ap;
	ab =b * 250;
	ad =d * 180;
	as =s * 150;
	ah =h *1200;
	ay =y *  50;
	af =f * 120;
	ap =p * 160;
	int total= ab+ad+as+ah+ay+af+ap;
	int dis= (total * 10)/100;
	int fprice= total - dis;
	System.out.println("+-------------------------------------------+        ");
	System.out.println("|         _ __  __            _             |        ");
     	System.out.println("|        (_)  \\/  |          | |            |       ");
	System.out.println("|         _| \\  / | __ _ _ __| |__          |       ");
	System.out.println("|        | | |\\/| |/ _' | '__| ___|         |       ");
	System.out.println("|        | | |  | | (_) | |  | |__          |        ");
	System.out.println("|        |_|_|  |_|\\__,_|_|  \\___|          |      ");
	System.out.println("|          225,Galle Road,Panadura.         |        ");
	System.out.println("+-------------------------------------------+        ");
	System.out.println("|            #Tel   : "+tel+ "            |          ");
	System.out.println("|            #Name  : "+name +  "                 |  ");
	System.out.println("+---------+--------+------------+-----------+        ");
	System.out.println("|         | Qty    | unit price |   Price   |        ");
	System.out.println("+-------------------------------------------+        ");
	System.out.println("|#Basmati |  "+b+"    |   250.0    |  "+ab+"     |        ");
	System.out.println("|#Dhal    |  "+d+"     |   180.0    |  "+ad+"      |      ");
	System.out.println("|#Sugar   |  "+s+"     |   150.0    |  "+as+"      |      ");
	System.out.println("|#Higland |  "+h+"     |  1200.0    |  "+ah+"     |       ");
	System.out.println("|#Yoghurt |  "+y+"     |    50.0    |  "+ay+"      |      ");
	System.out.println("|#Flour   |  "+f+"     |   120.0    |  "+af+"      |      ");
	System.out.println("|#Soap    |  "+p+"     |   160.0    |  "+ap+"      |      ");
	System.out.println("|         |        |            |           |             ");
	System.out.println("|---------+------+-+------------+-----------+             ");
	System.out.println("|                |    Total     |"+total+"       |         ");
	System.out.println("|                | Discount(10%)|"+dis+"        |          ");
	System.out.println("|                |   Price      |"+fprice+"       |        ");
	System.out.println("+-------------------------------------------+              ");
	int change,cash;
	System.out.print("Payment amount -");
	cash = print.nextInt();
	change = cash - fprice;
	System.out.println("+------------+------------------------------+             ");
	System.out.println("| Net Amount |   "+fprice+"                       |       ");
	System.out.println("+------------+------------------------------+             ");
	System.out.println("| Cash       |   "+cash+"                      |          ");
	System.out.println("+------------+------------------------------+             ");
	System.out.println("| Change     |   "+change+"                       |       ");
	System.out.println("+------------+------------------------------+             ");
	System.out.println("");
	System.out.println("");
	System.out.println("");
	System.out.println("");
	int n1,n2,n3,n4,n5,n6,n7;
	int c1,c2,c3,c4;
	n1 = change / 5000;
	change = change % 5000;
 	n2 = change / 2000;
	change = change % 2000;
 	n3 = change / 1000;
	change = change % 1000;
	n4 = change / 500;
	change = change % 500;
	n5 = change / 100;
	change = change % 100;
	n6 = change / 50;
	change = change % 50;
	n7 = change / 20;
	change = change % 20;
	c1 = change / 10;
	change = change % 10;
	c2 = change / 5;
	change = change % 5;
	c3 = change / 2;
	c4 = change % 2;
	int note = n1+n2+n3+n4+n5+n6+n7;
	int coin = c1+c2+c3+c4;
	System.out.println("+------------+------------------------------+             ");
	System.out.println("|  Value     |             No               |             ");
	System.out.println("+------------+------------------------------+             ");
	System.out.println("| Rs.5000    |             "+n1+"                |        ");
	System.out.println("+------------+------------------------------+             ");
	System.out.println("| Rs.2000    |             "+n2+"                |        ");
	System.out.println("+------------+------------------------------+             ");
	System.out.println("| Rs.1000    |             "+n3+"                |        ");
	System.out.println("+------------+------------------------------+             ");
	System.out.println("| Rs. 500    |             "+n4+"                |        ");
	System.out.println("+------------+------------------------------+             ");
	System.out.println("| Rs. 100    |             "+n5+"                |        ");
	System.out.println("+------------+------------------------------+             ");
	System.out.println("| Rs.  50    |             "+n6+"                |        ");
	System.out.println("+------------+------------------------------+             ");
	System.out.println("| Rs.  20    |             "+n7+"                |        ");
	System.out.println("+------------+------------------------------+             ");
	System.out.println("| Rs.  10    |             "+c1+"                |        ");
	System.out.println("+------------+------------------------------+             ");
	System.out.println("| Rs.   5    |             "+c2+"                |        ");
	System.out.println("+------------+------------------------------+             ");
	System.out.println("| Rs.   2    |             "+c3+"                |        ");
	System.out.println("+------------+------------------------------+             ");
	System.out.println("| Rs.   1    |             "+c4+"                |        ");
	System.out.println("+------------+------------------------------+             ");
	System.out.println("|No of Notes |             "+note+"                |      ");
	System.out.println("+------------+------------------------------+             ");
	System.out.println("|No of Coins |             "+coin+"                |      ");
	System.out.println("+------------+------------------------------+             ");
	System.out.println("");
	System.out.println("");
	System.out.println("------------------------------------------------------             ");
	System.out.println("          THANK YOU FOR SHOPPING WITH US                           ");
	System.out.println("------------------------------------------------------             ");
	}
}
